- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.dotfiles_local: ''
    ~/.gemini:
    ~/.gitconfig_local:
    ~/.hammerspoon:
    ~/.name:
    ~/.shell_local_after:
    ~/.shell_local_before:
