#!/usr/bin/env bash

# Credits:
# ~/.macos — https://mths.be/macos

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

###############################################################################
# General                                                                     #
###############################################################################

# Set appearance to Dark
defaults write NSGlobalDomain AppleInterfaceStyle Dark

# Set accent color to pink
defaults write NSGlobalDomain AppleAccentColor -int 6

# Set highlight color to pink
defaults write NSGlobalDomain AppleHighlightColor -string "1.000000 0.713725 0.756863 Light Pink"

# Set sidebar icon size to small
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 1

# Automatically hide and show the menu bar
defaults write NSGlobalDomain _HIHideMenuBar -bool true

# Show Bluetooth, Clock, Volume in menu bar
defaults write com.apple.systemuiserver menuExtras -array \
"/System/Library/CoreServices/Menu Extras/Bluetooth.menu" \
"/System/Library/CoreServices/Menu Extras/Clock.menu" \
"/System/Library/CoreServices/Menu Extras/Volume.menu"

# Always show scroll bars
# Possible values: "WhenScrolling", "Automatic", "Always"
defaults write NSGlobalDomain AppleShowScrollBars -string "Always"

# Click in the scroll bar to jump to the next page
defaults write NSGlobalDomain AppleScrollerPagingBehavior -bool false

# Disable iTunes when connecting devices
defaults write com.apple.iTunesHelper ignore-devices 1

###############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
###############################################################################

# Trackpad: enable tap to click for this user and for the login screen
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

###############################################################################
# Dock                                                                        #
###############################################################################

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Magnify the Dock
defaults write com.apple.dock magnification -bool true

# Set icon size to 16
defaults write com.apple.dock tilesize -int 16

# Set magnified icon size to 128
defaults write com.apple.dock largesize -int 128

# Show only open applications in the Dock
defaults write com.apple.dock static-only -bool true

# Set autohide delay to 0
defaults write com.apple.dock autohide-delay -float 0

###############################################################################
# Safari                                                                      #
###############################################################################

###############################################################################
# Finder                                                                      #
###############################################################################

###############################################################################
# Power Chime                                                                 #
###############################################################################

# Disable the chime when charging
defaults write com.apple.PowerChime ChimeOnNoHardware -bool true

###############################################################################
# Terminal                                                                    #
###############################################################################

# Use a modified version of the Solarized Dark theme by default in Terminal.app
osascript <<EOD

tell application "Terminal"

	local allOpenedWindows
	local initialOpenedWindows
	local windowID
	set themeName to "Solarized Dark xterm-256color"

	(* Store the IDs of all the open terminal windows. *)
	set initialOpenedWindows to id of every window

	(* Open the custom theme so that it gets added to the list
	   of available terminal themes (note: this will open two
	   additional terminal windows). *)
	do shell script "open '$HOME/dotfiles/init/" & themeName & ".terminal'"

	(* Wait a little bit to ensure that the custom theme is added. *)
	delay 1

	(* Set the custom theme as the default terminal theme. *)
	set default settings to settings set themeName

	(* Get the IDs of all the currently opened terminal windows. *)
	set allOpenedWindows to id of every window

	repeat with windowID in allOpenedWindows

		(* Close the additional windows that were opened in order
		   to add the custom theme to the list of terminal themes. *)
		if initialOpenedWindows does not contain windowID then
			close (every window whose id is windowID)

		(* Change the theme for the initial opened terminal windows
		   to remove the need to close them in order for the custom
		   theme to be applied. *)
		else
			set current settings of tabs of (every window whose id is windowID) to settings set themeName
		end if

	end repeat

end tell

EOD

###############################################################################
# Kill affected applications                                                  #
###############################################################################

for app in "cfprefsd" \
	"SystemUIServer" \
	"Dock" \
	"Safari" \
	"Finder" \
	"PowerChime" \
	"Terminal"; do
	killall "${app}" &> /dev/null
done
echo "Done. Note that some of these changes require a logout/restart to take effect."
